# DARK ENGINE - PRODUCTION CONFIGURATION
# ======================================

# METRICS
dark.metrics.server.port=13000

# THREADING
dark.system.threads.max=16

# PHYSICS
dark.physics.iterations=4
dark.physics.gravity.y=-9.81
